In [2]:
# input of Date, Bull_Prob, Bear_Prob, Sideways_Prob
# output should be Date, Signal, Position

In [3]:
# sample data
# Date,Bull,Bear,Sideways
# 2024-01-01,0.8,0.1,0.1
# 2024-01-02,0.7,0.2,0.1
# 2024-01-03,0.5,0.3,0.2
# 2024-01-04,0.2,0.7,0.1
# 2024-01-05,0.1,0.8,0.1
# 2024-01-06,0.3,0.2,0.5

In [7]:
import pandas as pd

def generate_signal(row, threshold):
    
    bull = row["Bull"]
    bear = row["Bear"]
    sideways = row["Sideways"]

    if bull > threshold :
        return "BUY"
    elif bear > threshold :
        return "SELL"
    elif sideways > threshold :
        return "HOLD"
    else :
        return "HOLD"

In [5]:
def generate_positon(row):
    bull = row["Bull"]
    bear = row["Bear"]

    position = bull - bear
    return round(position, 2)

In [1]:
# now then i will create a main.py for the testing
# import pandas as pd

# from signal.py import generate_signal
# from positons.py import generate_positon

# df = pd.readcsv("...")

# df["Signal"] = df.apply(
#     generate_signal,
#     axis=1
# )

# df["Position"] = df.apply(
#     generate_position,
#     axis=1
# )

# print(df)

# df.to_csv(
#     "../data/signals.csv",
#     index=False
# )

In [12]:
import pandas as pd
import os

path = os.path.realpath("analysis")
dir = os.path.dirname(path).replace("notebooks", "data")

os.chdir(dir)

df = pd.read_csv("state_probabilities.csv")
df

,State_0,State_1,State_2,State_3,State_4,State_5,Date
0,0.000000e+00,1.000000e+00,1.253288e-182,1.053696e-84,1.654023e-81,0.000000e+00,2010-02-02
1,1.061187e-26,7.921128e-01,6.957536e-10,1.490111e-03,2.063971e-01,4.468597e-57,2010-02-03
2,5.576504e-28,5.338382e-01,1.158662e-11,3.841877e-04,4.657776e-01,1.319821e-44,2010-02-04
3,2.656135e-41,1.546720e-02,8.278132e-20,2.678238e-03,9.818546e-01,3.140861e-62,2010-02-05
4,5.407933e-42,1.568410e-04,3.276641e-21,1.215314e-04,9.997216e-01,6.390727e-71,2010-02-08
...,...,...,...,...,...,...,...
3904,1.363407e-07,2.586535e-30,3.642998e-20,1.813887e-13,4.523270e-23,9.999999e-01,2025-12-24
3905,2.431137e-07,1.362581e-29,1.291100e-21,2.394574e-13,1.519576e-22,9.999998e-01,2025-12-26
3906,3.408675e-07,6.339430e-29,4.741365e-21,2.078952e-13,1.426003e-22,9.999997e-01,2025-12-29
3907,3.375738e-07,7.385335e-26,9.836050e-21,2.721738e-10,1.425978e-20,9.999997e-01,2025-12-30
3908,2.637172e-05,2.671123e-19,1.511305e-15,8.091548e-07,1.886166e-14,9.999728e-01,2025-12-31

In [23]:
import numpy as np

P = pd.read_csv("transition_matrix.csv").values

state_cols = [f"State_{i}" for i in range(6)]

def forecast(curr_regime_prob):
    return curr_regime_prob @ P

tomorrow_probs = pd.DataFrame(
    df[state_cols].apply(
        lambda row: forecast(row.values),
        axis=1
    ).tolist(),
    columns=state_cols
)

tomorrow_probs

,State_0,State_1,State_2,State_3,State_4,State_5
0,0.000046,9.227908e-01,4.985393e-02,0.006332,2.097661e-02,1.852386e-21
1,0.000437,7.387875e-01,3.955623e-02,0.006705,2.145150e-01,9.034795e-15
2,0.000833,5.100963e-01,2.663102e-02,0.004876,4.575636e-01,1.504604e-16
3,0.001763,5.123728e-02,8.902561e-04,0.004703,9.414058e-01,2.972722e-23
4,0.001712,3.760525e-02,1.322611e-05,0.002665,9.580043e-01,3.341357e-25
...,...,...,...,...,...,...
3904,0.036540,1.228244e-14,4.999565e-09,0.001937,1.430330e-14,9.615229e-01
3905,0.036540,1.621447e-14,8.914889e-09,0.001937,1.888227e-14,9.615228e-01
3906,0.036540,1.407728e-14,1.249948e-08,0.001937,1.639346e-14,9.615227e-01
3907,0.036540,1.842981e-11,1.239080e-08,0.001937,2.146211e-11,9.615227e-01
3908,0.036563,5.479060e-08,1.003040e-06,0.001938,6.380546e-08,9.614978e-01

In [27]:
tomorrow_probs.sum(axis=1)

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
3904    1.0
3905    1.0
3906    1.0
3907    1.0
3908    1.0
Length: 3909, dtype: float64